### ISSUE TITLE
Is it possible to create a release with support for node V4 and V5

### ISSUE THREAD

**Issue by pieter-v** [dfournier/broccoli-requirejs#19]
Support is already in head (https://github.com/dfournier/broccoli-requirejs/commit/5635746e6e09bba89b48aeb57b8b05fc85e05885)

Thanks

**Comment by dfournier** [comment]
Sure! I'll also add node 5.5 :wink:

**Comment by davidfou** [comment]
[Version 2](https://github.com/dfournier/broccoli-requirejs/releases/tag/v2.0.0) is live! I also made some updates on dependencies. Make sure you installed latest version dependencies.

Let me know if you have some issues with this version :wink:
