### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by monsterlane** [dfournier/broccoli-requirejs#23]
Hi I'm trying to figure out how to use this package.

```
package.json
Gruntfile.js
public/.htaccess
private/application/controllers/one/js/index.js
private/application/controllers/two/js/index.js
private/application/controllers/system/js/require.min.js
private/application/controllers/system/js/require.config.js
...
```

I'm trying to call this from Grunt. I know the require options are correct I can use grunt-contrib-requirejs with the same options object to build the project. When I try to make a task using this package like this I don't get any output:

```
grunt.registerTask( 'broccoli', function( ) {
	var rjs = require( 'broccoli-requirejs' );

	var t = new rjs( 'private/application/controllers', {
		verbose: true,
		requirejs: {
			baseUrl: 'private/application/controllers/',
			dir: 'public/files/cache/',
			mainConfigFile: 'private/application/controllers/system/js/require.config.js',
			optimize: 'uglify2',
			skipDirOptimize: true,
			generateSourceMaps: true,
			findNestedDependencies: true,
			preserveLicenseComments: false,
			fileExclusionRegExp: /^(\.|views)|(\.php)$/,
			paths: {
				'requirejs': 'system/js/require.min'
			},
			modules: modules
		}
	});
});
```

"modules" is an array I build by scanning the project structure for controllers. It looks like this:

```
[ { name: 'system/js/app' },
  { name: 'system/js/module' },
  { name: 'admin/js/bootstrap', exclude: [ 'jclass', 'jquery' ] },
  ... ]
```

I also tried making a test.js file and running it from Node. That looks like this:

```
var optimizeRequireJs = require( 'broccoli-requirejs' );

module.exports = new optimizeRequireJs( 'private/application/controllers', {
	verbose: true,
	requirejs: {
		baseUrl: 'private/application/controllers/',
		dir: 'public/files/cache/',
		mainConfigFile: 'private/application/controllers/system/js/require.config.js',
		optimize: 'uglify2',
		skipDirOptimize: true,
		generateSourceMaps: true,
		findNestedDependencies: true,
		preserveLicenseComments: false,
		fileExclusionRegExp: /^(\.|views)|(\.php)$/,
		paths: {
			'requirejs': 'system/js/require.min'
		},
		modules: modules
	}
});
```

I got that from https://github.com/dfournier/broccoli-requirejs/issues/6#issuecomment-68246758

I don't get any output on screen when I `node test.js`. If I remove the "new" operator I get an error but that's the only thing I can get it to do. I do not have a Brocfile.js and I'm using Node 7.4.0. I tried posting on [StackOverflow](https://stackoverflow.com/questions/45798317/broccoli-and-requirejs) and didn't receive any responses. Any idea what I'm doing wrong?

**Comment by davidfou** [comment]
Hi,

Are you trying to use this package on [Grunt](https://gruntjs.com/)?

**Comment by monsterlane** [comment]
Yes currently we use Grunt for our build/deploy. Currently it's compiled with [grunt-contrib-requirejs](https://github.com/gruntjs/grunt-contrib-requirejs) using the options object I posted above. Build times are upwards of 5 minutes so I'm trying to use your package to reduce the build times.

**Comment by davidfou** [comment]
Sorry but this package isn't compatible with Grunt. It must be used with [Broccoli.js](http://broccolijs.com/). Maybe you should try to move to [Webpack](https://webpack.github.io/).

**Comment by monsterlane** [comment]
Ok thanks for the quick reply!
